name: kanigara
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_search_bar: ^2.1.0
  excel: ^1.1.5
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/TempatMakan_Solo.xlsx
    - assets/Icon/24-hours.png
    - assets/Icon/bakery.png
    - assets/Icon/chinese-food.png
    - assets/Icon/confetti.png
    - assets/Icon/drinks.png
    - assets/Icon/fast-food.png
    - assets/Icon/fried-chicken.png
    - assets/Icon/healthy-food.png
    - assets/Icon/kebab.png
    - assets/Icon/kimchi.png
    - assets/Icon/latte.png
    - assets/Icon/love.png
    - assets/Icon/meatballs.png
    - assets/Icon/nearby.png
    - assets/Icon/nuggets.png
    - assets/Icon/onigiri.png
    - assets/Icon/piggy-bank.png
    - assets/Icon/pizza.png
    - assets/Icon/price-tag.png
    - assets/Icon/ramen.png
    - assets/Icon/rice.png
    - assets/Icon/satay.png
    - assets/Icon/shrimp.png
    - assets/Icon/star.png
    - assets/Icon/sweets.png
    - assets/Icon/take-away.png
    - assets/Icon/tomyam.png

